### ISSUE TITLE
Add a readme

### ISSUE THREAD

**Issue by dbelz** [UltimateCodeMonkeys/CodeMonkeysMVVM#12]
Add a readme. At least a basic one

**Comment by Pantheas** [comment]
Do it.

**Comment by dbelz** [comment]
Closed with PR: [#13](https://github.com/UltimateCodeMonkeys/CodeMonkeysMVVM/pull/13)

**Comment by dbelz** [comment]
Closed with PR: [#13](https://github.com/UltimateCodeMonkeys/CodeMonkeysMVVM/pull/13)
